In [ ]:
import torch

In [ ]:
print(torch.__version__)

## Creating tensors

In [ ]:
#Scalar
scalar = torch.tensor(7)
print(scalar)
print(f'dimenstions : {scalar.ndim}')
print(f"Value : {scalar.item()}")

In [ ]:
# Vector
vector = torch.tensor([7,9])
print(vector)
print(f"dimension : {vector.ndim}")


In [ ]:
# Matrix
matrix = torch.tensor([[7, 10, 10], [8,8,9]])
print(matrix)

## Random tensors

In [ ]:
random_tensor = torch.rand((1
                            ,6))
print(random_tensor)

### Zeros and Ones

In [ ]:
tensor_ones = torch.ones(size=(3,4
                            ))
print(tensor_ones)

In [ ]:
tensor_zeros = torch.zeros(size=(5,4))
print(tensor_zeros)

In [ ]:
tensor_zeros.dtype

## Range of tensors and tensors-like

In [ ]:
tensor_range = torch.range(1, 10, 2)
print(tensor_range)

In [ ]:
tensor_arange = torch.arange(1, 10, 2)
print(tensor_arange)

In [ ]:
#tensors like
tensor_like = torch.ones_like(tensor_zeros)

In [ ]:
tensor_like

# Tensor DataTypes

In [ ]:
int_tenor = torch.tensor([3, 2, 2], dtype=torch.int)

In [ ]:
int_tenor.dtype

In [ ]:
tensor_test = torch.tensor([3, 2, 2])

In [ ]:
tensor_test.dtype

In [ ]:
tensor_zeros = torch.zeros(size=(5,4), dtype=torch.int64)
print(tensor_zeros)

In [ ]:
tensor_zeros.dtype

### Tensor Manipulation

Tensor Operations:
 * Addition
 * Subtraction
 * Multiplication (element-wise)
 * Division
 * Matrix Multiplication

In [35]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_1 + 10

tensor([11, 12, 13])

In [36]:
#multiply tensor
tensor_1 = torch.tensor([1, 2, 3])
tensor_1 * 10

tensor([10, 20, 30])

In [37]:
#subtract
tensor_1 - 10

tensor([-9, -8, -7])

In [38]:
#Pytorch inbuilt
torch.mul(tensor_1, 10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor_1, 10)

tensor([11, 12, 13])

In [40]:
torch.sub(tensor_1, 10)

tensor([-9, -8, -7])

In [41]:
torch.div(tensor_1, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplicattion
* Element wise multiplication
* dot product or matrix

In [42]:
tensor_1

tensor([1, 2, 3])

In [43]:
print(f"Element wise multiplication {tensor_1}   *{ tensor_1}")

Element wise multiplication tensor([1, 2, 3])   *tensor([1, 2, 3])


In [45]:

tensor_1 * tensor_1

tensor([1, 4, 9])

In [46]:
#Matrix multiplication
torch.matmul(tensor_1, tensor_1)

tensor(14)

In [47]:
1*1 + 2*2 + 3*3

14

In [54]:
matrix_a = torch.tensor([[1, 2,3], [3,4, 3]])
matrix_b = torch.tensor([[5,6],[7,8], [1, 2]])

2 * 3,  3*2

In [55]:
result = torch.matmul(matrix_a, matrix_b)

In [51]:
result

tensor([[19, 22],
        [43, 50]])

In [56]:
matrix_a @ matrix_b

tensor([[22, 28],
        [46, 56]])